name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          MY_NAME: ${{ secrets.MY_LAST_NAME}}
          SURNAME: ${{ secrets.MY_LAST_NAME}}
          if[ "MY_LAST_NAME" -eq "Lopez" ]
          then
             echo "Got secret"
             fi
