name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Test
         run: |
           if [ "$MY_LAST_NAME" == "Lopez" ]
           then
              echo "Got secret"
           fi
      - uses: actions/checkout@v1
      - uses: ./
        with:
          MY_NAME: ${{ secrets.MY_NAME}}
          MY_LAST_NAME: ${{ secrets.MY_LAST_NAME}}

